// This file has been generated by Specta. DO NOT EDIT.

export type PlayerInformation = { id: string; token: string }

export type BoardPositionInformation = { board_position: string }

export type ValidMovesInformation = { valid_moves: { [key: string]: string[] }; special_moves: SpecialMove[] }

export type PlayerGameInformation = { id: string; token: string; color: string }

export type WebsocketMessage = { message_type: string; from: string; to: string; move_type: string; promotion_piece: string }

export type SpecialMove = { from_absolute: string; to_absolute: string; special_type: string }

