[package]
name = "admin_console"
version = "0.1.0"
edition = "2021"

[dependencies]
bunt = "0.2.8"
inquire = "0.7.5"
tokio = { version = "1.33.0", features = ["full"] }
chess_engine = { path = "../chess_engine" }
